### PR TITLE
Move version_jar_file to end of classpath

### PR DESCRIPTION
**Pull request by onebyte4**
minecraft launcher adds version_jar_file to end of classpath ,this pr fixes incompatibilities with some modded versions.

### CODE REVIEW

**Comment by mindstorm38** [comment]
Great! Thank you

**Comment by mindstorm38** [comment]
I need to create a branch and you'll need to re-target your PR onto it (no rebase should be needed on your side I wish)

**Comment by mindstorm38** [comment]
Hi! I created the branch `version/3.2.1`, could you retarget your merge?

**Comment by onebyte4** [comment]
retargeted to version/3.2.1

**Pull request merged**
